### ISSUE TITLE
4.0使用时提示赋值错误

### ISSUE THREAD

**Issue by Yorha4D** [scifx/blender-language-switcher#2]
![image](https://github.com/scifx/blender-language-switcher/assets/116185401/b98b2892-8aca-4dca-8978-372c61e38772)
Python: Traceback (most recent call last):
  File "C:\Users\YORHA\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blender-language-switcher-main\__init__.py", line 42, in invoke
    return self.execute(context)
  File "C:\Users\YORHA\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blender-language-switcher-main\__init__.py", line 37, in execute
    bpy.context.preferences.view.language = ('zh_HANS' if (bpy.app.version[0] >= 4) else 'zh_CN')
TypeError: bpy_struct: item.attr = val: enum "zh_HANS" not found in ('DEFAULT', 'en_US', 'es', 'ja_JP', 'sk_SK', 'vi_VN', 'zh_CN', 'ar_EG', 'de_DE', 'fr_FR', 'it_IT', 'ko_KR', 'pt_BR', 'pt_PT', 'ru_RU', 'uk_UA', 'zh_TW', 'ab', 'ca_AD', 'cs_CZ', 'eo', 'eu_EU', 'fa_IR', 'ha', 'he_IL', 'hi_IN', 'hr_HR', 'hu_HU', 'id_ID', 'ky_KG', 'nl_NL', 'pl_PL', 'sr_RS', 'sr_RS@latin', 'sv_SE', 'th_TH', 'tr_TR')
——————————————————————————————————————————————
  或许是版本判断错误？

**Comment by Yorha4D** [comment]
@scifx

**Comment by Yorha4D** [comment]
复现=英文切换中文

**Comment by pengjiaxusz** [comment]
\_\_init\_\_.py 第 37 行:
https://github.com/scifx/blender-language-switcher/blob/3ac24071fd9bff6d1022b3df5223ba762ea6d03d/__init__.py#L37
改成:
```python
bpy.context.preferences.view.language = "zh_CN" if "zh_CN" in bpy.app.translations.locales else "zh_HANS"
```
